### ISSUE TITLE
[기업]id와 비밀번호 체크시 Exception 처리 추가

### ISSUE THREAD

**Issue by minkeun428** [f-lab-edu/conference-reservation#52]
- 추가 / 개선 요소
회원 아이디 중복체크와 회원탈퇴 시 체크하는 로직에서
공통된 Exception처리가 필요하다.

- 추가 / 개선 이유
Service에서 로직 처리 후, boolean 리턴을 받을 때, Insert시 난 에러인지, 중복체크 시에 발생한 리턴 값인지 
구분하기 위해서이다.

**Comment by f-kei** [comment]
@minkeun428  merged 까지 되었다면 closed 를 해도 좋을것 같습니다!
