### ISSUE TITLE
Exception 처리에 관한 질문

### ISSUE THREAD

**Issue by minkeun428** [f-lab-edu/conference-reservation#55]
- 구현 사항
<img width="228" alt="스크린샷 2021-07-30 오후 4 18 50" src="https://user-images.githubusercontent.com/82353972/127616110-1228a17d-b1e3-440c-b75c-5d58c33ea6bc.png">

- 구현 이슈
I/O가 많이 일어나는 insert, delete, update에 대한 exception처리를 하기 위해 저렇게 별도로 구현해도 괜찮을까요?
아니면 보통 RumtimeException으로 묶어서 처리를 하는게 나을까요?
제가 3가지로 나눈 이유는
실수로 인한 쿼리 오작동, 무결성 제약 조건 위반 등이 발생하였을 때, 해당 에러를 처리하는 클래스가 나뉘어져 있으면 바로 파악하기 쉬울거라 생각했기 때문입니다!

@f-kei
@heo-ella

**Comment by f-kei** [comment]
클래스 파일이 많아지거나,  너무 많은 예외 클래스로 분리되지 않을까에 대한 염려는 하면서 감이 올거에요.

우선은 1개의 RuntimeException 을 사용한다면 우리는 RuntimeException('xxxx 에러입니다') 이런식으로 밖에 표현을 못하겠죠.
그럼 사람의 눈으로는 이해할 수 있겠죠,

하지만 그 Exception 을 받아서 그 외부에서 핸들링(제어) 해야 하는 경우에는 Exception 의 메시지를 뽑아내서 if err.getMessage.equals("xxx 메시지입니다)  이렇게  하는게 좋을까요??

github 에서 몇가지 다른 프로젝트의 링크를 첨부합니다.
* https://github.com/fuinorg/ddd-4-java/search?q=filename%3A*Exception.java
* https://github.com/draphyz/DDD/search?q=filename%3A*Exception.cs
